[package]
name = "routex-client-cxx"
version = "0.2.0"
build = "build.rs"
edition = "2024"
rust-version = "1.88"
publish = false
description = "C++ client for YAXI's Open Banking services"

[dependencies]
anyhow = "1.0.46"
chrono = { version = "0.4.34", default-features = false }
cxx = "1.0.150"
jsonwebtoken = { version = "10.1", default-features = false, features = ["rust_crypto"] }
paste = "1.0.2"
reqwest = { version = "0.13.2", features = ["rustls"] }
routex-api = "0.30.1"
routex-client = "0.20"
routex-client-common = { version = "0.0.5", features = ["error"] }
tokio = { version = "1.40", features = ["rt-multi-thread"] }
uuid = "1.5"

[build-dependencies]
cc = "1.2.62"
cxx-build = "1.0.50"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1.31"

[lib]
crate-type = ["staticlib", "cdylib"]

[profile.release]
codegen-units = 1

[package.metadata.winresource]
FileDescription = "YAXI Open Banking services client"
CompanyName = "YAXI GmbH"
